### PR TITLE
Add support for path parameters to handlebars `pathify`

### PR DESCRIPTION
**Pull request by mm-gmbd**
- A few quick tests seem to indicate that this works fine
- Was designed to replace multiple parameters, but needs to be tested
further
- Could probably be optimized down to a few lines, but this was
quick'n'dirty :)
- No error checking on value of pathParam -- should probably only be
allowed to be javascript native
- Only works globally -- I wonder if there is a way to make this easier
to do in a per-path fashion (right now, selfishly, it serves the purpose
I need it for)

### CODE REVIEW

**Comment by mm-gmbd** [comment]
Support for #91. After many commits to satisfy eslint, this passes the continuous integration tests.

**Comment by mm-gmbd** [comment]
Slight update: 

- Now, path parameters will be replaced in the form of {param} and/or
{{param}} (or however many curly braces are used)
- It should also match on sets of uneven curly braces, such as {param}},
this may be undesirable behavior

**Comment by mohsen1** [comment]
@noahdietz Can you review this?

**Comment by noahdietz** [comment]
@mohsen1 yeah I'll take a look
@mm-gmbd thanks for the PR

**Comment by noahdietz** [comment]
@mm-gmbd looks good to me. Thanks for adding this.

A couple things before it's accepted:
* Could you please add a test case for this functionality. You can add it to [test/pathParam/test.js](https://github.com/mm-gmbd/swagger-test-templates/blob/master/test/pathParam/test.js), with a corresponding "compare" file for diff testing.

* If you could squash your commits into 1 that would be very helpful for keeping our commit history clean/understandable (this was my first project with eslint, drove me crazy too)

**Comment by mm-gmbd** [comment]
@noahdietz, so I squashed all the commits and then synced with the PR and it looks like set *my* copy to the one with multiple commits rather then change the *PR* to be the squashed commit.

Should I open a separate PR and submit the single squashed commit there? Apologies -- I'm not quite a git aficionado :P

**Comment by mm-gmbd** [comment]
@noahdietz, also, I'm not very familiar with using Mocha or Chai (I've only used [Vows](http://vowsjs.org/) and that was quite recent.

This is as far as I've gotten on editing [tests](https://github.com/mm-gmbd/swagger-test-templates/blob/master/test/pathParam/test.js), but I'm not sure how the corresponding `output3-{id}-test.js` file should be written.

```javascript
describe('user-supplied pathParams', function(){
  var output3 = testGen(swagger, {
    assertionFormat: 'should',
    pathName: [],
    pathParams: {
      id: 'userSuppliedID'
    }
  });

  var paths3 = [];
  var ndx;

  for (ndx in output3) {
    if (output3) {
      paths3.push(join(__dirname, '/compare/output3-' + output3[ndx].name));
    }
  }


  it ('should have a substituted path parameter where "{id}" was', function() {
    //what goes here? how does it correspond to diff file?
  });
});
```

**Comment by noahdietz** [comment]
@mm-gmbd no problem, I can walk you through squashing. The tricky thing with squashing is that you have to overwrite the remote branch because the history is being rewritten, so it all has to work before you push or you will be SOL :)
* ```git log``` to view your commit history on the branch
* ```git rebase -i HEAD~[number of commits  back from head you want to squash]```
* this will take you into interactive mode. replace all of the commits marked ```pick``` that you want to squash into the previous one with ```squash```. save this file to continue.
* then you must craft a commit message from all of them. Just delete the individual commit messages and write one that reflects the functionality of the PR
* test to make sure nothing broke in the squashing
* ```git log``` to make sure all of the commits you squashed are now gone, replaced by the single squashed commit. this is what your commit history will look like after pushing to remote
* ```git push -f origin [branch name]``` to revise remote branch

I think the part you were missing was forcing the push to remote.

**Comment by noahdietz** [comment]
@mm-gmbd as for the test...

The compare file should be an exact match of the generated test code. We run a diff test against them. You can copy one of the other compare files, change the file name and update the path in the the tests to reflect the replacement you implemented.

For example, this is a snippet of generated test code:
```js
it('should respond with 200 OK', function(done) {
      api.get('/userSuppliedID') // this is the expected output of your added functionality
      .set('Accept', 'application/json')
      .expect(200)
      .end(function(err, res) {
        if (err) return done(err);

        res.body.should.equal(null); // non-json response or no schema
        done();
      });
    });
```

Your unit test (the ```it('message', function(done) { ... });``` block) can match the ones [before](https://github.com/mm-gmbd/swagger-test-templates/blob/master/test/pathParam/test.js#L97) it, but with your updated message and changed output number (output2 --> output3)

Keep asking questions if you need to! Happy to help.

**Comment by mm-gmbd** [comment]
@noahdietz, thanks for the pointers. Yeah, the `git push -f origin` step was what I had missed. I was using the GitHub Desktop client and, after rebasing, just pressed "Sync".

A quick question -- will the test suite be run automatically when I push the latest version? Just wondering if I need to run it on my end.

**Comment by mm-gmbd** [comment]
@noahdietz, squashed into a single commit successfully and test have been written and passed (and eslint is happy!). Thanks for the help!

**Comment by noahdietz** [comment]
@mm-gmbd Well done, thank you for contributing to this project. Merging

**Pull request merged**
