### PR TITLE
change file naming convention

### PR DESCRIPTION
**Pull request by elsapeng**
changed file name convention, so for path /xxx, it will be xxx-test.js
used sanitize-filename module to sanitize filenames
wrote tests for this feature

fixed issue #22

### CODE REVIEW

**Comment by mohsen1** [comment]
Do we have tests that ensures file names are correct? If no, write some tests that check against any edge case you can think of.

**Comment by elsapeng** [comment]
I write some tests for it, but maybe not enough, will add more

**Comment by mohsen1** [comment]
Yes, please add edge cases like special characters in path.

**Comment by mohsen1** [comment]
@elsapeng please rebase

**Comment by elsapeng** [comment]
Ok

**Pull request merged**
