### PR TITLE
Add API spec in the README

### PR DESCRIPTION
**Pull request by mohsen1**
Fixes the first item in #77

@noahdietz @elsapeng

### CODE REVIEW

**Comment by elsapeng** [comment]
@mohsen1, updated :)

**Comment by elsapeng** [comment]
Also, right now the first 3 config items are required, we can change to optional and set default value (we did that in swagger-node, but not in this module) if you think this make more sense @mohsen1 @noahdietz

**Comment by mohsen1** [comment]
No, no need to change the program because of the docs. If the load test stuff is not in master yet, let's hold on to it and add it later. Other than that it looks good. Thanks for fixing it.

**Comment by noahdietz** [comment]
thanks for changing this @elsapeng! looks good

**Comment by elsapeng** [comment]
updated :)

**Comment by mohsen1** [comment]
:+1:

**Comment by elsapeng** [comment]
thank you!

**Pull request merged**
