### PR TITLE
Feature/user mock data

### PR DESCRIPTION
**Pull request by Remco75**
@noahdietz @mm-gmbd I took the liberty to fork your PR's, merge some other needed branches in it and make all the tests pass, and added some tests.

I changed some of the variable names to keep ik more generic, and a little less tied to one specific mock generator framework. 

We need a fix for get requests, I did not get to that yet.
But lets merge this first!

### CODE REVIEW

**Comment by Remco75** [comment]
and it builds!! ;-)
@mm-gmbd , @noahdietz can you review? We can close a lot after this , and finally release!

**Comment by Remco75** [comment]
#107 is included in this PR, so we can close that one if we merge this.
#114 is includes as well I think

**Comment by noahdietz** [comment]
I want @mm-gmbd 's approval and then I will squash & merge

**Comment by Remco75** [comment]
@mm-gmbd we need you! :-)

**Comment by Remco75** [comment]
Gentlemen, what are w gonna do? I really would like to release! 
@mm-gmbd , are you still onboard? ;-)

**Comment by mm-gmbd** [comment]
@Remco75, I just got back into the country after being gone for a month. Work has been wild. I need to catch up on life and work, but I will try to get caught up on this soon.

**Comment by mm-gmbd** [comment]
All -- sorry for the radio silence -- as I stated above I've been out of the country for a month and haven't had any time to keep up with this. I will get caught up soon - I'm glad everyone has been pushing forward :smile:

**Comment by Remco75** [comment]
Just added the population of get request mock data as well. Turned out to be quite easy, as we could use existing functionality :-)

Just transfer the requestMock data to the pathParams.
We expect the paramers the be properties if the requestData object, (just as we do for the body)

**Comment by Remco75** [comment]
fixed readme, comments, improvements welcome!

**Comment by mm-gmbd** [comment]
Hola amigos! I've got a bit of time to look into this now. Just got @Remco75's branch pulled into my own and checking it out...

FYI -- I'm sure everything in here is great, so don't hold up on account of me at this point (especially considering how detached I've been), but I'll be sure to provide comments/suggestions if I've got any. Thanks!

**Pull request merged**
