### PR TITLE
Instagram tests

### PR DESCRIPTION
**Pull request by noahdietz**
does not assert on lint errors from generated tests because we have to handle verbose descriptions and formatting within 80char limit, addressed in issue #14

### CODE REVIEW

**Comment by mohsen1** [comment]
I'm wondering if it's going to be a hassle to maintain in the long run. It's good to see what it produces but maintaining the compression files can be time consuming.

**Comment by noahdietz** [comment]
@mohsen1 yeah this is why before I hadn't made a full suite, i used it to test the specific functionality that i was working on with a large swagger. we can keep it locally and take a look at it when we need to test something specifically?

**Comment by mohsen1** [comment]
Yes, lets keep Instagram as a manual test target.

**Comment by mohsen1** [comment]
Can we close this?

**Pull request closed without merging**
