### PR TITLE
change description maxLen truncation toggle

### PR DESCRIPTION
**Pull request by noahdietz**
* passing `maxLen: -1` toggles off all test description truncation, the `length` helper becomes a `noop`
* updated README to reflect this option
* changes `.eslintrc` to allow longer line length in source files

Refers to discussion in #107

### CODE REVIEW

**Comment by noahdietz** [comment]
@Remco75 please review when you get a chance. It is quite small.

@mm-gmbd I noticed in your PR that you had the Handlebars helpers in another folder. I like the idea, I think I did that on my own fork too but never merged it...configurable variables will have to be exported via `helpers.js` and set by `index.js`. Just a heads up that you'll have to add it to your PR. 😄

**Comment by Remco75** [comment]
Nice job, lgtm! One remark, would be nice to only truncate if the user explicitly asks for it. So, in absence of the minLength config you get the full description (makes a bit more sense to me, but I don't know about historical reasons.
So, if you want to keep it this way: merge it

On a completely unrelated note: while writing tests I noticed we have a lot of code duplication (for instance, to load the compare code). 
Might be handy to write a helper function for it. But that's for a new PR

**Comment by mm-gmbd** [comment]
@noahdietz - I moved the helpers to their own file based on what I saw in your fork :)

**Comment by noahdietz** [comment]
@Remco75 I would refer you to the conversation we had on #107 prior to your arrival in the data-generation conversation. Its a matter of generating valid javascript consistently. I'd rather a user be "upset" that their description was truncated and turn off truncation then have to go through each test file and change stuff. In any other situation, i'd agree, making functionality that mutates user info off by default is convention.

@mm-gmbd perfect! Think I should make a PR on your fork to include it in your PR rather than making you redo this work to merge yours? I can just copy + paste most of the stuff, and add the variable export to `helpers.js`....it'll be pretty simple.

**Comment by Remco75** [comment]
@noahdietz in that case, merge it!

**Comment by noahdietz** [comment]
@mm-gmbd I copied this into a PR for your repo, but I don't have permission to make a new repo! so if you don't mind doing the work to merge your PR and after this one, then I will merge this. Otherwise, if you could give me some permissions on your repo, I'd be happy to submit the change there so you don't have to!

**Comment by noahdietz** [comment]
This will be closed when [#4](https://github.com/mm-gmbd/swagger-test-templates/pull/4) from mm-gmd's fork is merged and #107 is merged to master

**Pull request closed without merging**
