### PR TITLE
package.json: Bump json-schema-deref-sync

### PR DESCRIPTION
**Pull request by DeeDeeG**
Bumps json-schema-deref-sync to "^0.6.0".

json-schema-deref-sync 0.3.x depends on an old version of mpath that has a vulnerability report open against it (see `npm audit` or `yarn audit`).

This is the smallest version bump possible for json-schema-deref-sync in order to bump the indirect dependency on mpath to greater than mpath 0.5.1. That's good enough to get rid of the vulnerability warning for mpath.

---

Note that using caret "`^`" semver effectively locks json-schema-deref-sync to 0.[n].x in this case, e.g. 0.6.x; that's because caret semver only allows versions that don't change the leftmost non-zero digit, in this case 0.**6**.x (See the node semver docs for details: https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004 )

json-schema-deref-sync is up to 0.11.x now, so if newer versions would work, feel free to bump the version even higher instead.

### CODE REVIEW

**Comment by DeeDeeG** [comment]
I'm not really familiar with the code in this project, but this patch seems to do bad things in CI. Hmm.

https://travis-ci.org/apigee-127/swagger-test-templates/jobs/589188001#L230

**Comment by DeeDeeG** [comment]
The error seems to be a syntax error in json-schema-deref-sync itself. Will try progressively newer versions and stick with the first one that passes, if any...

**Comment by DeeDeeG** [comment]
apparently all newer versions of json-schema-deref-sync expect node 6+, according to commints in this PR.

https://github.com/cvent/json-schema-deref-sync/pull/11

As CI for this repo uses node 0.12 and 4.4.5, it seems like CI will always fail for recent-enough versions of this dependency.

Suggested solution: Support only node 6+ in the next release of swagger-test-templates? (Or ignore the vulnerability report?)

**Comment by DeeDeeG** [comment]
Bumping json-schema-deref-sync passes Travis CI on Node v6 or up.
Example passing Travis run: https://travis-ci.org/apigee-127/swagger-test-templates/jobs/590575923

That would mean that this npm module would require Node 6+. That version of Node came out in [April 2016](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.0.0).

**Comment by DeeDeeG** [comment]
This passes CI now. I edited `.travis.yml` to only test against Node v6 and v10. v6 is the minimum this package would work on now, and v10 is the current LTS release of Node, although soon v12 will be the LTS release of Node.

The last commit in this branch edits the `package.json` to warn users if they attempt to install this package using Node v5.x or lower. Arguably redundant, since the version of `json-schema-deref-sync` used in this branch produces an identical warning, but probably useful to make it more obvious how/why users' code might have broken if installing this update.

Recommend possibly doing a major release (v1.x) if merging this, since it breaks the package on Node v5.x and older.

**Comment by DeeDeeG** [comment]
Hi, is there any interest in this PR?

I am using the [`swagger`](https://github.com/swagger-api/swagger-node) node package in a project, which depends on `swagger-test-templates`. In this way I am pulling in `swagger-test-templates`, and the last remaining security issue I have in my audits is this outdated dependency on `json-schema-deref-sync`.

It would help me and other `swagger` users stay more secure if this (indirect) dependency could be updated.

(I'd note that the `swagger` node package is largely unmaintained, and has `"swagger-test-templates": "^1.2.0"` in its `package.json`. So it will only pick up a new release of this package in the 1.x series. A new 2.x release of this package would require `swagger` accepting a pull request to bump this package to 2.x in their `package.json`... But I suppose that's not really this project's responsibility. Just thought it would be worth pointing out.)

**Comment by noahdietz** [comment]
Released in 1.6.0

**Comment by DeeDeeG** [comment]
Thank you! 

(While this is the last issue I can see to fix in this repo, I mis-remembered this as the "last" issue for `swagger` -- There are dependencies in other repos that probably need tiny PRs. I'll try to track them down... Anyway thanks again! One down, several more to go...)

**Pull request merged**
