### PR TITLE
Feature/add new swagger schematypes

### PR DESCRIPTION
**Pull request by Remco75**
Added some current swagger schema types to the Z-schema validator, with some base validation as well. This can be more complete but I ran out of time. 

It is partly based on the ideas of #99, but with added testing. #99 can be closed if this one is merged as well

### CODE REVIEW

**Comment by Remco75** [comment]
Currently the build fails on a very old node version... should be fixed when #109 is fixed

**Comment by Remco75** [comment]
also, there are commits in there form a former PR, that were not squashed.... sorry, should have no effects

**Comment by Remco75** [comment]
#104

**Comment by noahdietz** [comment]
@Remco75 you might rebase this branch against master to include the Travis Node.js version change, I just merged it. :)

**Comment by Remco75** [comment]
Done, all signals green again :-)
This is the final fix for issue #104 
It also makes PR #99 done, so these can be closed when this one is merged (and everybody agrees)

**Comment by noahdietz** [comment]
lgtm! well done! :)

**Pull request merged**
